import { createMuiTheme } from "@material-ui/core/styles";
import { COLORS } from "./constant";

const theme = createMuiTheme({
  palette: {
    primary: {
      main: COLORS.emerald,
      contrastText: COLORS.white,
    },
    secondary: {
      main: COLORS.rockBlue,
      dark: COLORS.algaeGreen,
    },
    warning: {
      main: COLORS.yellowOrange,
    },
    success: {
      main: COLORS.chateauGreen,
    },
    common: {
      black: COLORS.mineShaft,
      white: COLORS.white,
    },
    error: {
      main: COLORS.red,
    },
    background: {
      default: COLORS.athensGray,
      paper: COLORS.white,
    },
    text: {
      primary: COLORS.bluewood,
      secondary: COLORS.shuttleGray,
      hint: COLORS.santasGray,
    },
    action: {
      hover: COLORS.lightGray,
      hoverOpacity: 0.2,
    },
    status: {
      info: COLORS.sunshade,
    },
  },
  typography: {
    fontFamily: "Montserrat, sans-serif",
    button: {
      fontFamily: "Montserrat, sans-serif",
      textTransform: "none",
      fontSize: "14px",
      fontWeight: "600",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: "1.29",
      letterSpacing: "0.2px",
      textAlign: "center",
      color: "#ffffff",
    },
    h1: {
      fontSize: "100px",
      fontWeight: 300,
      fontFamily: "Montserrat, sans-serif",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "0.2px",
    },
    h2: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "32px",
      fontWeight: 600,
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.31,
      letterSpacing: "0.1px",
      textAlign: "left",
      color: COLORS.bigStone,
    },
    h3: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "26px",
      fontWeight: 500,
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.23,
      letterSpacing: "0.2px",
      textAlign: "center",
      color: COLORS.bigStone,
    },
    h4: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "18px",
      fontWeight: 500,
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.33,
      letterSpacing: "0.2px",
      textAlign: "left",
      color: COLORS.nevada,
    },
    h5: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "14px",
      fontWeight: 600,
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.29,
      letterSpacing: "0.2px",
      textAlign: "center",
      color: COLORS.white,
    },
    h6: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "14px",
      fontWeight: "normal",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.57,
      letterSpacing: "0.1px",
      textAlign: "left",
      color: COLORS.nevada,
    },
    subtitle1: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "18px",
      fontWeight: 500,
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.33,
      letterSpacing: "0.2px",
      textAlign: "left",
      color: COLORS.oxfordBlue,
    },
    subtitle2: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "12px",
      fontWeight: 500,
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.33,
      letterSpacing: "0.2px",
      textAlign: "left",
      color: COLORS.bigStone,
    },
    body1: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "14px",
      fontWeight: 500,
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.29,
      letterSpacing: "0.1px",
      textAlign: "left",
      color: COLORS.bigStone,
    },
    body2: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "12px",
      fontWeight: "normal",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.33,
      letterSpacing: "0.2px",
      textAlign: "left",
      color: COLORS.nevada,
    },
    navtabs: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "16px",
      fontWeight: 500,
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.5,
      letterSpacing: "0.1px",
      textAlign: "left",
      color: COLORS.nevada,
    },
    overline: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "10px",
      fontWeight: 500,
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: 1.6,
      letterSpacing: "0.2px",
      textAlign: "left",
      color: COLORS.crimsonRed,
    },
  },
  spacing: 4,
});
export default theme;
