export default {
  ADD_YOUR_LOCATION: "ADD_YOUR_LOCATION",
  ADD_JOB_LOCATIONS: "ADD_JOB_LOCATIONS",
  ADD_SKILLS: "ADD_SKILLS",
  ADD_JOBS: "ADD_JOBS",
  SET_SAVED_JOBS: "SET_SAVED_JOBS",
  ADD_SAVED_JOB: "ADD_SAVED_JOB",
  REMOVE_SAVED_JOB: "REMOVE_SAVED_JOB",
  APPLY_FILTER: "APPLY_FILTER",
  REMOVE_FILTER: "REMOVE_FILTER",
  ADD_FILTERED_JOBS: "ADD_FILTERED_JOBS",
  REMOVE_FILTERED_JOBS: "REMOVE_FILTERED_JOBS",
  REMOVE_EACH_FILTER: "REMOVE_EACH_FILTER",
};
